name: SSH Deployment

# Controls when the action will run.
on:
  push:
    branches: [app_version_A]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: login to the production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          whoami
          pwd
